andela/bp-esa-backend

.gitignore
.sequelizerc
db/migrations/20180716094129-createUserTable.js
db/migrations/20180716094745-createPartnerTable.js
db/migrations/20180716095453-createSlackIntegrationTable.js
db/migrations/20180716105845-createFreckleIntegrationTable.js
db/migrations/20180716110542-createEmailIntegrationTable.js
package-lock.json
package.json
server/models/emailIntegration.js
server/models/freckleIntegration.js
server/models/index.js
server/models/partner.js
server/models/slackIntegration.js
server/models/user.js

This PR introduces the database models to be used in the project as referenced in issue  #1

create database models

---

.eslintignore
.eslintrc.js
package-lock.json
package.json
server/config/config.js
server/controllers/index.js
server/index.js
server/models/emailIntegration.js
server/models/freckleIntegration.js
server/models/index.js
server/models/partner.js
server/models/slackIntegration.js
server/models/user.js

This pull request adds linting to the project via eslint using the Airbnb Javascript StyleGuide
- Open your terminal on the root folder of the application
- Make to install all the `eslint` npm packages by running the `npm install` command
- run the `npm run lint` command

eslint integration

---

.circleci/config.yml
.env.example
.eslintrc.js
.gitignore
README.md
package-lock.json
package.json
server/config/config.js
test/models/emailIntegrationModel.test.js
test/models/freckleIntegrationModel.test.js
test/models/partnerModel.test.js
test/models/slackIntegrationModel.test.js
test/models/userModel.test.js
test/setup.js

This PR adds tests for models.

Add models' tests.

---

README.md

This PR updates the README.md to ensure smooth on-boarding for anyone interested in the project
The following sections were added to the README:-
- The name of the project
- Brief description
- Technologies used
- Prerequisites
- How to contribute
- Style guides and conventions to follow.
[#160437408](https://www.pivotaltracker.com/story/show/160437408)

#160437408 Update the README.md

---

.env.example
.sequelizerc
db/migrations/20180716094129-createUserTable.js
db/migrations/20180716094745-createPartnerTable.js
db/migrations/20180716095453-createSlackIntegrationTable.js
db/migrations/20180716105845-createFreckleIntegrationTable.js
db/migrations/20180716110542-createEmailIntegrationTable.js
package.json
server/config/config.js

This PR removes cascading deletes from tables created by  the database migrations

Prevent cascading deletes in db migrations

---

.env.example
README.md
docs/swagger.js
docs/swagger/user.yaml
package-lock.json
package.json
server/index.js

-  Introduce '**ESA**' API documentation using swagger
-  Aims to make product management a breeze- helps other internal teams know the details of  resources, methods, and their associated requests and responses, making maintenance and updates quicker.
- Developers and other user alike will be able to integrate the ESA API as quickly as possible.
clone the repo
- `cd` into the project dir
- git-checkout to branch `ch-api-documentation-swagger`
- install application requirements with `npm install`
- use the information in `.env.sample` to provide the necessary environment variables i `.env`
- use `npm run start:dev` to start the application
- note that the default port is `8000`
- access sample swagger api documentation from the browser
> Documentation is one of the most important factors …

API Documentation Swagger

---

.circleci/config.yml
.gitignore
package-lock.json
package.json

Integrate CodeClimate service for quality assurance
- When a developer a raises a PR, CodeClimate should display rating for test coverage
- When a developer a raises a PR, CodeClimate should display the quality assurance of the code and highlight issues to be fixed if exists
- CodeClimate badge should be attached to readme to display the quality rating (maintainability) of the entire codebase
N/A
Previously when a PR is raised, there is no way to check for test coverage of the changes made, nor its impact on the codebase. Also, the maintainability of implemented code could not be ascertained. With Code-climate, the team is informed just how well the code base are tested and have a maintainability report on PRs and the codebase at large, so as to be able to know areas to refactor and what …

#161544689 Code climate setup

---

server/modules/slackIntegration.js

This pull request is a replica of https://github.com/andela/bp-esa-backend/pull/31
The main pull request #31 has code-climate issues, but for the purpose of project-demo, the `ft-slack-integration` branch would be merged into the `demo-branch`.

Demo - create channels for new engagements

---

server/helpers/response.js
server/modules/freckle/projects.js

create a project on Freckle if it does not exist before.
- Create a function that check fetches all projects.
- Create a function that checks if name of project to be created exists in fetched projects.
- Create a new project on freckle workspace or respond with a message indicating project already exists.
- execute the function `createProject` with string argument of the name of the project to be created
- check the freckle workspace to verify if project was created created.
N/A
[#161875603](https://www.pivotaltracker.com/story/show/161875603)
N/A
N/A

#161875603 Create new freckle project

---

.eslintrc.js
server/helpers/response.js
server/modules/freckle/projects.js
server/modules/slack/slackIntegration.js

- add JSDoc rule in ESLint configuration
- add JSDoc comments to some functions that are yet to be commented
- modify the JSDoc comments that are not properly written
Enforce the use of JSDoc Commenting.
- Try creating a function without adding JSDoc comments.
- Run the lint command in the root dir of the project `npm run lint`
- The function without JSDoc comment should be flagged.
None
#161950268

#161950268 Enforce the use of JSDoc Commenting

---

server/jobs/index.js
server/jobs/offboarding/sampleJob.js
server/jobs/onboarding/sampleJob.js

- create a job folder to hold all the jobs(automation)
- create a job reader program to read and export the jobs
- create some sample jobs
Create a job reader program
#162198074

#162198074 Jobs Reader

---

server/index.js
server/jobs/index.js
server/jobs/offboarding/sampleJob.js
server/jobs/onboarding/sampleJob.js
server/modules/allocations.js
test/modules/allocations.test.js

- modify the logic for setting default interval for the worker
- did a bit of refactoring of the allocations module
- add sample jobs to explain the signature of a job
BUG: When TIMER_INTERVAL is not set in the environment variables, the app crashes.
1. Checkout to the branch containing the changes of this Pull Request(`bg-timer-interval-error-162192966`)
2. Run the command to start the app, `npm run start:dev`
3. The app should no longer be crashing and it should start fine
#162192966

 #162192966 Fix worker time-interval error

---

server/jobs/onboarding/freckle.js
server/jobs/worker.js
server/modules/allocations.js
server/modules/freckle/projects.js

Implement automation for adding new engagement on freckle
Integrate function that adds engagements to freckle with the background worker
Run the app and log into freckle dashboard to verify if new project was added.
- fetch data for all engagements
- loop through each engagement
- call the function that adds the project to freckle with partner name.
[#162081330](https://www.pivotaltracker.com/story/show/162081330)
N/A
N/A

#162081330 Add freckle-onboarding automation

---

.env.example
db/migrations/20180716094745-createPartnerTable.js
db/migrations/20180716095453-createSlackIntegrationTable.js
db/migrations/20180716105845-createFreckleIntegrationTable.js
db/migrations/20180716110542-createEmailIntegrationTable.js
package-lock.json
package.json
server/config/config.js
server/models/index.js
server/models/partner.js
test/models/partnerModel.test.js

- modify the partner model/migration
- remove all unnecessary associations to partner model
- update the config/setup of sequelize
- update the `.env.example`
- add a script for undoing migrations
Create a model(s) and generate migration(s) for the Partner data type
- Checkout to the branch that contains the changes on this PR(`ch-partner-data-type-162192990`)
- You should see an updated partner model in the models folder
- Run `npm run undo:migrations` on the CLI to undo any previous migrations
- Run `npm run migrations` on the CLI to migrate the new models into the database.
#162192990

#162192990 Create partner data type

---

package-lock.json
server/helpers/slackHelpers.js
server/jobs/offboarding/slack.js
server/jobs/onboarding/slack.js
server/modules/slack/slackIntegration.js
test/modules/slackIntegration.spec.js

Refactor slack integrations to eliminate redundant codes
- `catch` statements which return error should be removed so that the error would be thrown when the function is called
- `catch` blocks which just throws an exception should be removed
- redundant `createChannel` function which adds cognitive complexity to the implementation should be removed and implementation refactored
- redundant `channelExists` function which is useless since slack api throws an error when the channel to be created already exists, should be removed
- redundant `returnValidChannels` function which is based on redundant `channelExists` function should be removed, being no longer needed
1. Call the various functions in the module and log their output
2. On terminal, run command `npx babel-node …

#162548574 Refactor slackIntegrations

---

db/migrations/20181210091511-createSlackAutomationTable.js
db/operations/automations.js
package-lock.json
package.json
server/config/config.js
server/jobs/index.js
server/jobs/onboarding/slack.js
server/models/automation.js
server/models/emailAutomation.js
server/models/freckleAutomation.js
server/models/index.js
server/models/slackAutomation.js
server/modules/allocations.js
server/modules/slack/slackIntegration.js
server/validator.js
test/mocks/slack.js
test/models/automation.test.js
test/models/emailAutomation.test.js
test/models/freckleAutomation.test.js
test/models/slackAutomation.test.js
test/modules/slackIntegration.spec.js

- create functions to help persist automation to DB
- modify the database config file
- change casing of model names to lowercase
- modify the type enum in slackAutomation schema
- remove validation for environment variables that are not used
- update the model tests
- update the slackIntegration tests
Persist the result of slack automation.
- Checkout to the branch containing the changes of this Pull Request(`ch-persist-slack-automatn-result`)
- Run `npm run undo:all:migrations` on the CLI to undo any previous migrations
- Run `npm run migrations` on the CLI to migrate the updated models into the database.
- Run `start:dev` to start the app
- As soon as there is a new placement from allocatios, the automations would be executed and the result for slackAutomation would be persisted to the …

#162414292 Persist the result of slack automation

---

server/jobs/onboarding/freckle.js
server/modules/freckle/projects.js

Refactor freckle integration to be able to persist automation results to database
- Refactor freckle integrations to allow a result to be saved to the db per action
- Ensure all errors are caught and returned for each freckle automation
- Remove redundant `getProjectByName` function not required for creating a project on freckle 
1. Call the various functions in the module and log their output
2. On terminal, run command `npx babel-node erver/modules/freckle/projects.js`
3. Watch the terminal to confirm the function works as expected
N/A
[#162636968](https://www.pivotaltracker.com/story/show/162636968)
N/A

#162636968 Refactor freckle automation

---

.circleci/config.yml
server/index.js

Fix fetch data

---

server/index.js

Fix CORS Policy Error
1. Start the application
2. Call the application end point and check if the values 
```
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Origin: *
```
are present in the header

Fix CORS Error

---

.env.example
package-lock.json
package.json
server/controllers/automationController.js
server/index.js
server/jobs/index.js
server/jobs/onboarding/slack.js
server/modules/allocations.js
server/modules/automations.js
server/modules/email/emailModule.js
server/modules/slack/slackIntegration.js
test/endpoints/mockAndelapi.test.js
test/jobs/executejobs.test.js

Implement real-time feed for automation data
- install http and socket.io modules
- emit socket messages after automation are carried out
Can be tested when frontend part is implemented
None
[#164276272](https://www.pivotaltracker.com/story/show/164276272)
**newAutomation**
```
{
"id": 87,
"fellowId": "e80123b8-e18c-4d5f-a8ec-7167ebce1cd3",
"fellowName": "Samara, Lakin",
"partnerId": "-KXGyJcC1oimjQgFj184",
"partnerName": "Morar and Sons",
"type": "offboarding",
"createdAt": "2019-03-11T09:44:55.659Z",
"updatedAt": "2019-03-11T09:44:55.659Z",
"slackAutomations": {
"status": "success",
"slackActivities": [
{
"status": "success",
"statusMessage": "p-spinkaziemeandc-int slack channel created",
"type": "create",
"channelId": "GGTPPTH3J",
"channelName": "p-spinkaziemeandc-int",
"slackUserId": …
```

#164276272 Real-time automation feed

---

package-lock.json
server/controllers/automationController.js
server/modules/automations.js
test/endpoints/automations.test.js

- Returns pagination data
- This will provide a smaller chunk of a report to the user, help him/her to read the report page easier and also include parameter based filtering.
1. Clone the project and run it
2. On an app like Postman, send url in this format `/api/v1/automations?page={int}&limit={int}`; 
**limit** being the number of items you expect the pagination to return, and **page** being the page number: **### example below**
[#164396754](https://www.pivotaltracker.com/n/projects/2197045/stories/164396754)

#164396754 Ft Add Pagination

---

db/migrations/20190129094751-addEmailToAutomation.js
server/models/automation.js
server/utils/formatter.js

This adds email automation to the automation table data

added email to automation table

---

Dockerfile.dev
debug-compose.yml
docker-compose.yml
package.json

Enables migration to run when you use docker-compose
1. On terminal, run command docker-compose up
docker must be installed on system

Ch allow for easy migration with docker

---

server/jobs/helpers.js
server/jobs/index.js
server/jobs/offboarding/email.js
server/jobs/offboarding/slack.js
server/jobs/onboarding/email.js
server/jobs/onboarding/freckle.js
server/jobs/onboarding/slack.js
server/mockAndelaApi/index.js
server/modules/email/emailModule.js
server/modules/freckle/projects.js
server/modules/slack/slackIntegration.js
test/mocks/slack.js
test/modules/slackIntegration.spec.js

Refactor automations to eliminate side-effects
- ensure integration function returns value
- save automation results under jobs functions instead of within integration
- cleanup use of mutable AUTOMATION_ID env variable in passing automationId
- pass automationId as argument from jobs to automation functions
1. Set `TIMER_INTERVAL` environment variable to `45s`
2. On terminal, run command: `npm start`
3. Wait for several automations to execute
4. Check the database to confirm that automationIds do not overlap across different automations
Due to dynamic setting of `AUTOMATION_ID` env variable, which is being read when creating a new automation, a first automation whose execution time overlap with a second automation could have the automation data of the second saved under the first because …

#164946457 Refactor automations to eliminate side-effects

---

package-lock.json
package.json
server/controllers/automationController.js
server/modules/slack/slackIntegration.js
server/utils/formatter.js
server/utils/rawSQLQueries.js
test/endpoints/automations.test.js
test/endpoints/mockAndelapi.test.js
test/helpers/helpers.test.js

- Returns filtered data with pagination
- Implement filtering criterion when fetching automation data.
1. Clone the project and run it
2. The url **MUST HAVE** `page` and `limit` params. 
The rest of the params are optional. They can all be included or you can choose which combination to send.
[#164396754](https://www.pivotaltracker.com/story/show/164396754)

#164691350 Add filter functionality

---

server/controllers/automationController.js
server/modules/slack/slackIntegration.js
test/endpoints/automations.test.js
test/jobs/executejobs.test.js

update to search query parameters
now search query parameter which was previously `q` and `queryTerm` is now `searchTerm` and `searchBy`

change search parameters
